/*
 * This source file was generated by the Gradle 'init' task
 */
package cse311;

import java.io.IOException;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        SimpleMemory memory = new SimpleMemory(8 * 1024 * 1024);
        MemoryManager memoryManager = new MemoryManager(memory);
        RV32iCpu cpu = new RV32iCpu(memoryManager);
        
        // Keep the main thread alive while the WebSocket server is running
        try {
            while (true) {
                Thread.sleep(1000);
            }
        } catch (InterruptedException e) {
            System.err.println("Server interrupted: " + e.getMessage());
        }
    }
}
